<?php

/**
 * @file
 * Explains how a module declares theme functions, preprocess functions, and
 * templates.
 *
 * The underlying approach is that a module should allow themes to do all
 * rendering, but provide default implementations where appropriate.
 *
 * For a more descriptive introduction to creating a module that uses the
 * theme layer, see http://drupal.org/node/165706.
 */

/**
 * Implements hook_menu().
 */
function theming_example_menu() {
  $items['examples/theming_example'] = array(
    'title'            => 'Basic Theming Example',
    'description'      => 'Some theming examples.',
    'page callback'    => 'theming_example_basic_content',
    'access callback'  => TRUE,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_theme().
 *
 * Defines the theming capabilities provided as default representations by this module.
 *
 * A theme can override these default implementations.
 *
 * This hook_theme() is really an informational note to Drupal.  It tells Drupal :
 *   Hey, this module wants to enable rendering beyond the return of a straight string.
 *   This module wants to let themes override the way returned data can be portrayed.
 *   The theme can either override via a theme function (first case below) or a
 *   template file (second case below).
 *   As part of this "theme info passing to Drupal", this hook tells Drupal the
 *   name of the function that is overridable, and the name of the 'arguments' (variables)
 *   which the module is passing off and are themable.
 *
 * @see http://api.drupal.org/api/drupal/developer--hooks--core.php/function/hook_theme/6
 */
function theming_example_theme() {
  return array(
    'theming_example_basic_content' => array(
      // 'arguments' are a required ke for D6.
      'arguments' => array('content' => NULL),
    ),
  );
}

/**
 * Initial landing page explaining use of the module.
 * This is the page callback for the simple implementation (no template).
 */
function theming_example_basic_content() {
  $content = t('Most simple example of returning content with page callback. No templates nor theme functions.');
  $content = theme('theming_example_basic_content', $content);
  return $content;
}

